### ISSUE TITLE
[Bug] SRAI does not assemble correctly

### ISSUE THREAD

**Issue by 64** [carlosedp/riscvassembler#19]
```scala
      println(RISCVAssembler.binOutput("srai x0, x0, 0"))
```
outputs `00000000000000000101000000010011`, but it should print `01000000000000000101000000010011`.

**Comment by carlosedp** [comment]
Thanks for reporting this!
Published v1.6.1 which will be up in some minutes!

**Comment by carlosedp** [comment]
I borked the fix since I appended zeroes while the correct would be using the shamt.

Will fix it properly soon.

**Comment by carlosedp** [comment]
Now we are good to go :)
